image: ubuntu

stages:
    - test

deploy-dev:
    stage: test
    only:
        - web
    script:
        - apt-get install python3.8
        - pip install --user -r requirements.txt 
        - pip install --user pytest
        - pytest
