#image: nefrock/docker-mega-net-cpu

# image: ubuntu

stages:
    - test

# test-dev:
#     stage: test
#     only:
#         - web
#     script:
#         - pip3 install -r requirements.txt
#         - pip3 install --user pytest
#         - pip3 list

# cache:
#   paths:
#     - .pip
#
# before_script:
#   - mkdir -p .pip
#   - pip install -U pip
#   - pip --cache-dir=.pip install -r tests_requires.txt

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
    paths:
        - .cache/pip


deploy-dev:
    stage: test
    tags:
        - docker
    image: orgoro/dlib-opencv-python
    only:
        - web
    script:
        - pip3 install -r requirements.txt
        - pip3 list
        - pwd
        - ls -l
        - export PYTHONPATH="$PYTHONPATH:./swagger_server"
        - python -c "import sys;print(sys.path)"
        - pytest swagger_server/tests/test_jwt.py
        # - apt-get -yq update
        # - apt-get -yq install software-properties-common
        # - add-apt-repository -y ppa:deadsnakes/ppa
        # - apt-get update -qy
        # - apt-get install -y python-dev python3-pip
        # - apt-get install -y cmake
        # - pytest
