#image: nefrock/docker-mega-net-cpu

# image: ubuntu

tags:
    - docker

image: orgoro/dlib-opencv-python

stages:
    - test

# test-dev:
#     stage: test
#     only:
#         - web
#     script:
#         - pip3 install -r requirements.txt
#         - pip3 install --user pytest
#         - pip3 list

deploy-dev:
    stage: test
    only:
        - web
    script:
        - pip3 list
        # - apt-get -yq update
        # - apt-get -yq install software-properties-common
        # - add-apt-repository -y ppa:deadsnakes/ppa
        # - apt-get update -qy
        # - apt-get install -y python-dev python3-pip
        # - apt-get install -y cmake
        # - pip3 install -r requirements.txt
        # - pip3 install --user pytest
        # - pytest
