stages:
    - unittest
    - integratetest
    - e2etest

# cache:
#   paths:
#     - .pip
#
# before_script:
#   - mkdir -p .pip
#   - pip install -U pip
#   - pip --cache-dir=.pip install -r tests_requires.txt

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
    paths:
        - .cache/pip

before_script:
    - pip3 install -r requirements.txt
    - pip3 list
    - pwd
    - ls -l
    - export PYTHONPATH="$PYTHONPATH:./swagger_server"
    - python -c "import sys;print(sys.path)"

unit-test-jwt:
    stage: unittest
    tags:
        - docker
    image: orgoro/dlib-opencv-python
    only:
        - web
    script:
        - pytest swagger_server/tests/test_jwt.py
        
#unit-test-modules:
#    stage: unittest
#    tags:
#        - docker
#    image: orgoro/dlib-opencv-python
#    only:
#        - web
#    script:
#        - pytest swagger_server/tests/test_module.py
#        
#unit-test-data:
#    stage: unittest
#    tags:
#        - docker
#    image: orgoro/dlib-opencv-python
#    only:
#        - web
#    script:
#        - pytest swagger_server/tests/test_data_access.py

integrate-test-mocking:
    stage: integratetest
    tags:
        - docker
    image: orgoro/dlib-opencv-python
    only:
        - web
    script:
        #- pytest swagger_server/tests/test_int_mocking.py
        - pytest swagger_server/tests/test_jwt.py
        
integrate-test-no-mocking:
    stage: integratetest
    tags:
        - docker
    image: orgoro/dlib-opencv-python
    only:
        - web
    script:
        #- pytest swagger_server/tests/test_int_no_mocking.py
        - pytest swagger_server/tests/test_jwt.py
        
e2e-test:
    stage: e2etest
    tags:
        - docker
    image: orgoro/dlib-opencv-python
    only:
        - web
    script:
        #- pytest swagger_server/tests/test_e2e.py
        - pytest swagger_server/tests/test_jwt.py
