image: ubuntu

stages:
    - test

deploy-dev:
    stage: test
    only:
        - web
    script:
        - apt-get install software-properties-common
        - add-apt-repository ppa:deadsnakes/ppa
        - apt-get update
        - apt-get install python3.8
        - pip install --user -r requirements.txt 
        - pip install --user pytest
        - pytest
